Port = 8080
Timeout = 120
AccessTokenSecret = "asdjklasjdlkasd"
AccessTokenExpiryHour = 2
RefreshTokenSecret = "asjdklasjdlasd"
RefreshTokenExpiryHour = 168

[DB]
Driver = "mysql"
Host = "localhost"
Port = "3306"
User = "root"
Pwd = "wrywan123"
Name = "go-test"

[Redis]
Host = "localhost"
Port = "6379"